function u = GetDataChunk(dataindices,filehandle,field,chunk_size,...
    locality,chunk_begin,chunk_end,rear_overlap,forward_overlap)

u = zeros(chunk_size + 2*locality, numel(dataindices)); % this will be populated by the input data to the reservoir

if locality > 0
    if rear_overlap(end)<rear_overlap(1)
        u(1:locality,:) = [filehandle.(field)(dataindices, ...
            rear_overlap(rear_overlap>rear_overlap(end))),...
            filehandle.(field)(dataindices, ...
            rear_overlap(rear_overlap<=rear_overlap(end)))]';
    else
        u(1:locality,:) = filehandle.(field)(dataindices,rear_overlap)';
    end

    if forward_overlap(end) < forward_overlap(1)
        u(locality+chunk_size+1:2*locality+chunk_size,:) = ...
            [filehandle.(field)(dataindices,...
            forward_overlap(forward_overlap>forward_overlap(end))),...
            filehandle.(field)(dataindices,...
            forward_overlap(forward_overlap<=forward_overlap(end)))]';
    else
        u(locality+chunk_size+1:2*locality+chunk_size,:) = ...
            filehandle.(field)(dataindices,forward_overlap)';
    end
end

u(locality+1:locality+chunk_size,:) = ...
    filehandle.(field)(dataindices, chunk_begin:chunk_end)';