function u = GetDataChunk(dataindices,filehandle,field,chunk_size,...
    locality,chunk_begin,chunk_end,rear_overlap,forward_overlap)

u = zeros(chunk_size + 2*locality, numel(dataindices)); % this will be populated by the input data to the reservoir

if locality > 0
    if rear_overlap(1,end)<rear_overlap(1,1)
        u(1:locality,:) = [filehandle.(field)(1:resparams.discard_length, ...
            rear_overlap(1,rear_overlap(1,:)>rear_overlap(1,end))),...
            filehandle.(field)(1:resparams.discard_length, ...
            rear_overlap(1,rear_overlap(1,:)<=rear_overlap(1,end)))]';
    else
        u(1:locality,:) = filehandle.(field)(1:resparams.discard_length,rear_overlap(1,:))';
    end

    if forward_overlap(end,end) < forward_overlap(end,1)
        u(locality+chunk_size+1:2*locality+chunk_size,:) = ...
            [filehandle.(field)(1:resparams.discard_length,...
            forward_overlap(end,forward_overlap(end,:)>forward_overlap(end,end))),...
            filehandle.(field)(1:resparams.discard_length,...
            forward_overlap(end,forward_overlap(end,:)<=forward_overlap(end,end)))]';
    else
        u(locality+chunk_size+1:2*locality+chunk_size,:) = ...
            filehandle.(field)(1:resparams.discard_length,forward_overlap(end,:))';
    end
end

u(locality+1:locality+chunk_size,:) = ...
    filehandle.(field)(1:resparams.discard_length, chunk_begin:chunk_end)';